### ISSUE TITLE
Call Py_CompileString at compile time

### ISSUE THREAD

**Issue by m-ou-se** [dronesforwork/inline-python#3]
It should be possible to call `Py_CompileString` at compile time (in the proc macro), and only store the Python bytecode in the Rust binary. That should save both space and parsing time in the resulting binary.

**Comment by m-ou-se** [comment]
This would also show the user any Python syntax errors during compile time instead of only at run time.

**Comment by tbodt** [comment]
This issue, and the entire project, is both amazing and horrifying

**Comment by de-vri-es** [comment]
Implemented with #5 :balloon:
